### ISSUE TITLE
Possible to test clowncar?

### ISSUE THREAD

**Issue by devinivy** [asilvas/json-stream-bench#1]
I've created a library called [clowncar](https://github.com/devinivy/clowncar), which is also a streaming JSON parser based upon [json-depth-stream](https://github.com/indutny/json-depth-stream).  The thing is, it targets a specific use-case, with the hope that limiting it to this one use-case will allow it to be faster than other streaming JSON implementations.  It's meant only to parse array items out of incoming JSON.  Do you think it would be possible to include a benchmark of it here, or would it be too hard or undesirable to include a library that can't run every test?

**Comment by asilvas** [comment]
Feel free to issue a PR if you'd like it included in the benchmarks. Happy to have contributions!

**Comment by devinivy** [comment]
I looked into this, but the existing tests weren't a good fit for clowncar because the data-sources aren't setup to be streamed as multiple chunks over time.  If I find time in the future I can try to broaden the tests in this repo to be even more stream-like (e.g. reading chunks into memory from a file or a socket to a separate node process).  Thanks @asilvas– I'm closing this for now but will comment back here if I come back around to it.
